// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs_co1p4kPH6QvvHUdT_V9Ms1ojtmRMnI',
    appId: '1:884714637661:web:85c4a68002b897f8ea00b4',
    messagingSenderId: '884714637661',
    projectId: 'ai-powered-bas',
    authDomain: 'ai-powered-bas.firebaseapp.com',
    storageBucket: 'ai-powered-bas.firebasestorage.app',
    measurementId: 'G-9KNMMLDHE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'demo-android-api-key',
    appId: '1:demo-project:android:demo-android-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'demo-project-id',
    storageBucket: 'demo-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-ios-api-key',
    appId: '1:demo-project:ios:demo-ios-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'demo-project-id',
    storageBucket: 'demo-project-id.appspot.com',
    iosBundleId: 'com.example.bloodAvailabilitySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-ios-api-key',
    appId: '1:demo-project:macos:demo-macos-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'demo-project-id',
    storageBucket: 'demo-project-id.appspot.com',
    iosBundleId: 'com.example.bloodAvailabilitySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:demo-project:web:demo-windows-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'demo-project-id',
    authDomain: 'demo-project-id.firebaseapp.com',
    storageBucket: 'demo-project-id.appspot.com',
  );
}
