"""Initial schema

Revision ID: b1f9a8196f28
Revises: 
Create Date: 2025-11-10 23:21:42.278456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1f9a8196f28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('blood_type', sa.Enum('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other'), nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('available_for_donation', sa.Boolean(), nullable=True),
    sa.Column('total_donations', sa.Integer(), nullable=True),
    sa.Column('has_chronic_diseases', sa.Boolean(), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('rating', mysql.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('response_time_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hospital_type', sa.Enum('Government', 'Private', 'Trust', 'Military'), nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=False),
    sa.Column('has_blood_bank', sa.Boolean(), nullable=True),
    sa.Column('total_beds', sa.Integer(), nullable=True),
    sa.Column('icu_beds', sa.Integer(), nullable=True),
    sa.Column('emergency_beds', sa.Integer(), nullable=True),
    sa.Column('departments', sa.Text(), nullable=True),
    sa.Column('facilities', sa.Text(), nullable=True),
    sa.Column('rating', mysql.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('operating_hours', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.Enum('Donor', 'Hospital', 'User'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('BloodRequest', 'Match', 'Reminder', 'Alert', 'Info', 'Emergency'), nullable=False),
    sa.Column('priority', sa.Enum('High', 'Medium', 'Low'), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('inventory_a_positive', sa.Integer(), nullable=True),
    sa.Column('inventory_a_negative', sa.Integer(), nullable=True),
    sa.Column('inventory_b_positive', sa.Integer(), nullable=True),
    sa.Column('inventory_b_negative', sa.Integer(), nullable=True),
    sa.Column('inventory_ab_positive', sa.Integer(), nullable=True),
    sa.Column('inventory_ab_negative', sa.Integer(), nullable=True),
    sa.Column('inventory_o_positive', sa.Integer(), nullable=True),
    sa.Column('inventory_o_negative', sa.Integer(), nullable=True),
    sa.Column('operating_hours_weekdays', sa.String(length=50), nullable=True),
    sa.Column('operating_hours_weekends', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('last_inventory_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('blood_type', sa.Enum('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'), nullable=False),
    sa.Column('units_required', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Enum('Critical', 'Urgent', 'Normal'), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('requester_name', sa.String(length=100), nullable=True),
    sa.Column('requester_phone', sa.String(length=20), nullable=True),
    sa.Column('requester_email', sa.String(length=100), nullable=True),
    sa.Column('requester_relation', sa.String(length=50), nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Matched', 'Fulfilled', 'Cancelled', 'Expired'), nullable=True),
    sa.Column('required_by', sa.DateTime(), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_request_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_request_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('match_score', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('distance_km', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('responded', sa.Boolean(), nullable=True),
    sa.Column('response_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blood_request_id'], ['blood_requests.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blood_request_matches')
    op.drop_table('blood_requests')
    op.drop_table('blood_banks')
    op.drop_table('notifications')
    op.drop_table('hospitals')
    op.drop_table('donors')
    # ### end Alembic commands ###
